version: "3"
services:
  fms-bot:
    build:
      context: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.1-bullseye
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "fms" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./psql-init:/docker-entrypoint-initdb.d
