version: "3"
services:
  fms-bot:
    image: ${FULL_IMAGE_NAME}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
#   does not supported yet in docker swarm - https://github.com/docker/compose/issues/9957
#    depends_on:
#      postgres:
#        condition: service_healthy

  postgres:
    image: postgres:15.1-bullseye
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "Shop" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./psql-init:/docker-entrypoint-initdb.d
      - /psql-data:/var/lib/postgresql/data/pgdata
